move to file initialization for tests (#1785)
Example failures - 


https://github.com/facebookresearch/fairchem/actions/runs/21956906560/job/63423418778

https://github.com/facebookresearch/fairchem/actions/runs/21958279229/job/63428406208

```
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 44217, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
```